/* Editable Gate 3 drawing source. Buyer text follows the owner-approved P005 Full Copy. */
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const deps = 'C:/Users/longe/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules';
const {chromium} = require(path.join(deps, 'playwright'));
const out = __dirname;
const arrow = '<svg class="ui-icon" aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M6 18 18 6M6 6h12v12"/></svg>';
const email = 'mailto:jenny@ge-masterbatch.com?subject=Product%20document%20question';
const brand = '<a class="brand" href="/" aria-label="GE Chemical homepage"><img src="../P001/assets/ge-logo-candidate.png" alt="GE Chemical &amp; Polymer Group Co., Ltd."></a>';
const nav = '<a href="/products/black-masterbatch">Black Masterbatch</a><a href="/products">Products</a><a href="/applications">Applications</a><a href="/about">About GE</a>';
const inquiry = `<a class="btn primary header-cta" href="/rfq">Discuss Your Requirements${arrow}</a>`;
const header = `<header class="site-header"><div class="shell header-inner">${brand}<nav class="desktop-nav" aria-label="Primary navigation">${nav}</nav><div class="tablet-inquiry">${inquiry}</div><details class="mobile-menu"><summary>Menu <span class="menu-open">☰</span><span class="menu-close">×</span></summary><nav aria-label="Mobile navigation">${nav}${inquiry}</nav></details></div></header>`;
const footerColumn = (label, links) => `<div class="footer-column"><p class="footer-title">${label}</p><nav aria-label="${label}">${links.map(([t,u])=>`<a href="${u}">${t}</a>`).join('')}</nav></div>`;
const footer = `<footer class="site-footer"><div class="shell footer-grid"><div class="footer-identity">${brand}<p>Binzhou, Shandong, China</p>${inquiry}</div>${footerColumn('Products',[['Black Masterbatch','/products/black-masterbatch'],['White Masterbatch','/products/white-masterbatch'],['Color Masterbatch','/products/color-masterbatch'],['Desiccant Masterbatch','/products/desiccant-defoaming-masterbatch']])}${footerColumn('Company',[['About GE','/about'],['Manufacturing &amp; Quality','/manufacturing-quality']])}${footerColumn('Information',[['Applications','/applications'],['Product Documents','/documents'],['Masterbatch Questions','/faq']])}</div></footer>`;
const card = (num,question,kind,body)=>`<article class="decision-card"><span class="card-number">${num}</span><h3>${question}</h3><p class="document-kind">${kind}</p><p>${body}</p></article>`;
const models = ['BK020','BK025','BK030','BK035','BK040','PT-300','PT-450P'].map(x=>`<li>${x}</li>`).join('');
const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>P005 — Gate 3 visual draft</title><link rel="icon" type="image/png" href="../P001/assets/ge-brandmark-candidate.png"><link rel="stylesheet" href="p005-visual.css"></head><body><aside class="draft-note">P005 · Gate 3 visual draft · Planned links shown for layout review</aside>${header}<main>
<section class="hero module"><div class="shell hero-layout"><div class="hero-copy"><h1>Masterbatch Technical Documents</h1><p>Find the technical document that fits your product review. This guide shows which GE models have technical data sheets (TDS), what the Black Masterbatch safety data sheet (SDS) covers, and how to ask about a document.</p><div class="actions"><a class="btn primary" href="${email}">Ask GE About a Document${arrow}</a></div><p class="email-note">This opens an email draft in your email application; you need to send it. If the link does not open, copy <strong>jenny@ge-masterbatch.com</strong> into your email application.</p></div><div class="document-art" aria-hidden="true"><div class="art-sheet sheet-back"></div><div class="art-sheet sheet-mid"></div><div class="art-sheet sheet-front"><div class="art-rule"></div><div class="art-rule short"></div><div class="art-rule"></div><div class="art-rule medium"></div><div class="art-grid"><i></i><i></i><i></i><i></i></div></div></div></div></section>
<section class="choice module"><div class="shell"><div class="section-grid"><div class="section-heading"><h2>Choose the Document for Your Review</h2></div><div class="decision-list">${card('01','What technical information is recorded for a named GE model?','Technical Data Sheet (TDS)','A TDS presents technical information for the model named on the sheet. Match your model to the list below.')}${card('02','What safety, handling or material information is stated?','Safety Data Sheet (SDS, sometimes called MSDS)','An SDS provides safety information for its identified product. Ask GE to check its relevance to your grade.')}${card('03','What was tested for a particular sample?','Sample test report','A report records results for the identified sample and tests. Ask about one if your review calls for a specific test record.')}</div></div><p class="choice-note">If your customer needs a batch-specific record or certificate of analysis (COA), describe the requirement in your message for GE to review.</p></div></section>
<section class="tds module"><div class="shell section-grid"><div class="section-heading"><h2>Technical Data Sheets by Model</h2><p>GE has technical data sheets for these <strong>black masterbatch models</strong>:</p></div><div class="section-body"><ul class="model-list">${models}</ul><p>A separate TDS covers <strong>DM2476G desiccant masterbatch</strong>. Each sheet concerns its named model. Request the TDS for the model you are evaluating; GE will check its current version before sharing it privately. These documents are provided through an inquiry, with no public downloads on this page.</p><p>For the black product range, <a href="/products/black-masterbatch">Explore Black Masterbatch${arrow}</a>.</p></div></div></section>
<section class="safety module"><div class="shell section-grid"><div class="section-heading"><h2>Safety Information and Specific Test Records</h2></div><div class="section-body"><p>GE has an SDS titled <strong>Black Masterbatch</strong>. It does not name a BK or PT model. Tell GE which grade you are evaluating so it can check applicability and the current version before sharing the SDS privately.</p><p>For a specific test-document requirement, tell GE which sample or test you need to review. Sample test reports relate only to the identified sample and tests; GE can check the relevant record and its scope.</p></div></div></section>
<section class="closing module"><div class="shell section-grid"><div class="section-heading"><h2>Tell GE What You Need to Review</h2></div><div class="section-body"><p>In your email, tell us the document type you need and the product or model, if you know it. Include the intended use or the customer requirement you are checking. If you have not chosen a model, describe your product interest and question so GE can help identify a relevant document.</p><div class="actions"><a class="btn primary" href="${email}">Email GE About Documents${arrow}</a></div></div></div></section>
</main>${footer}</body></html>`;
fs.writeFileSync(path.join(out,'p005-visual.html'),html);
(async()=>{const browser=await chromium.launch({headless:true});for(const width of [1440,768,390]){const page=await browser.newPage({viewport:{width,height:900},deviceScaleFactor:1});await page.goto(pathToFileURL(path.join(out,'p005-visual.html')).href);await page.screenshot({path:path.join(out,`p005-${width}.png`),fullPage:true});const check=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,height:document.documentElement.scrollHeight,images:[...document.images].every(i=>i.complete&&i.naturalWidth>0),models:document.querySelectorAll('.model-list li').length,links:[...document.querySelectorAll('main a[href^="mailto:"]')].map(a=>a.getAttribute('href'))}));if(check.scroll>width||!check.images||check.models!==7||check.links.length!==2||check.links[0]!==check.links[1])throw Error(`${width}: ${JSON.stringify(check)}`);console.log(width,check);await page.close()}await browser.close()})().catch(e=>{console.error(e);process.exitCode=1});
